[package]
name = "game_lib"
version = "0.1.0"
authors = ["Jakob Schwab <j.schwab@mail.de>"]

[dependencies]
cgmath = "0.16"
lodepng = "2.3"
rgb = "0.8"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
log = "0.4"
fern ="0.5"
failure = "0.1"