[package]
name = "game_runtime"
version = "0.1.0"
authors = ["Jakob Schwab <j.schwab@mail.de>"]

[dependencies]
gfx = "0.17"
gfx_window_glutin = "0.25"
glutin = "0.17"
rand = "0.5.4"
log = "0.4.3"
fern = "0.5.6"
libloading = "0.5"

[dependencies.game_lib]
path = "../game_lib"

